module.exports={
    entry:'./entry.js',
    output:{
        filename:'./bundle.js',   
    },
    module:{
        loaders:[
            {
                test:/\.css$/,
                loader:'style-loader!css-loader'   
            },
            {
                test:/\.scss$/,
                loader:'style-loader!css-loader!sass-loader'   
            }
        ]
    }
}
